### ISSUE TITLE
Error 'Undefined offset' in Bf4

### ISSUE THREAD

**Issue by OleksandrWebLab** [Austinb/GameQ#335]
```
exception 'ErrorException' with message 'Undefined offset: 27' in /home/.../vendor/austinb/gameq/src/GameQ/Protocols/Bf4.php:108
Stack trace:
#0 /home/.../vendor/austinb/gameq/src/GameQ/Protocols/Bf4.php(108): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(8, 'Undefined offse...', '/home/admin/web...', 108, Array)
#1 [internal function]: GameQ\Protocols\Bf4->processDetails(Object(GameQ\Buffer))
#2 /home/.../vendor/austinb/gameq/src/GameQ/Protocols/Bf3.php(186): call_user_func_array(Array, Array)
#3 /home/.../vendor/austinb/gameq/src/GameQ/GameQ.php(559): GameQ\Protocols\Bf3->processResponse()
#4 /home/.../vendor/austinb/gameq/src/GameQ/GameQ.php(331): GameQ\GameQ->doParseResponse(Object(GameQ\Server))
#5 /home/.../models/Server.php(53): GameQ\GameQ->process()
....
#25 {main}
```

If you comment out line 108 - the error disappears

**Comment by Austinb** [comment]
Does any one know if the protocol has changed?  That is the last item in the list and is blaze_game_state

**Comment by Austinb** [comment]
Does anyone have documentation for the server query and if it has changed recently in bf4?  Can anyone else reproduce this issue?

**Comment by Austinb** [comment]
Please reopen with more information.
