### ISSUE TITLE
[SAMP] GameQ throwing exception when the server address is a domain

### ISSUE THREAD

**Issue by RikoDEV** [Austinb/GameQ#588]
PHP: 8.1

Broken example:
```php
$api = new \GameQ\GameQ();
$api->addServer([ 'type' => 'Samp', 'host' => "game.samp-mobile.com:7777" ]);
$info = $api->addFilter('normalize')->process();

print_r($info);
```

Working example:
```php
$api = new \GameQ\GameQ();
$api->addServer([ 'type' => 'Samp', 'host' => "80.66.82.242:7777" ]);
$info = $api->addFilter('normalize')->process();

print_r($info);
```

Exception
```yaml
chr(): Argument #1 ($codepoint) must be of type int, string given {"exception":"[object] (TypeError(code: 0): chr(): Argument #1 ($codepoint) must be of type int, string given at /var/www/base/vendor/austinb/gameq/src/GameQ/Protocols/Samp.php:129)
[stacktrace]
#0 [internal function]: chr()
#1 /var/www/base/vendor/austinb/gameq/src/GameQ/Protocols/Samp.php(129): array_map()
#2 /var/www/base/vendor/austinb/gameq/src/GameQ/GameQ.php(473): GameQ\\Protocols\\Samp->beforeSend()
#3 /var/www/base/vendor/austinb/gameq/src/GameQ/GameQ.php(350): GameQ\\GameQ->doQueries()
```

**Comment by bumbummen99** [comment]
@RikoDEV Can you please check if #593 fixed this issue for you?

**Comment by RikoDEV** [comment]
> @RikoDEV Can you please check if #593 fixed this issue for you?

Yeah, It's fixed for me.
